### ISSUE TITLE
r5c

### ISSUE THREAD

**Issue by yuanjinhua2019** [sbwml/builder_test#1]
进不了路由后台

**Comment by sbwml** [comment]
接入网线  led 灯亮不亮？

**Comment by yuanjinhua2019** [comment]
亮

**Comment by sbwml** [comment]
你把电脑接入到 wan 口  ，看看电脑能不能获取到 10.0.0.x  的dhcp 地址？ 因为我没有这个设备  ，我不清楚它的网口是怎么样的

**Comment by yuanjinhua2019** [comment]
不可以，试过了

**Comment by sbwml** [comment]
你可以分别把电脑网线接到 r5c 的两个网口，提供电脑获取到的ipv4地址给我吗

![image](https://user-images.githubusercontent.com/16485166/220349195-2d5e4a61-1ceb-49ec-8b52-99a1e09172bd.png)

**Comment by yuanjinhua2019** [comment]
重启后wan口接到电脑可以获到地址10.0.0.1进入后台

**Comment by sbwml** [comment]
网口我可能配置错了 ，请问有QQ等联系方式吗，我想远程看一下nanopi r5c 这个机器

**Comment by yuanjinhua2019** [comment]
2679233578
