### ISSUE TITLE
qemu error

### ISSUE THREAD

**Issue by 0x2l** [sbwml/builder_test#2]
i can't run this image in qemu. This is my qemu flags:
```
qemu-system-x86_64 -M q35 \
-drive file=/home/nik/Downloads/openwrt-23.05.3-x86-64-generic-squashfs-combined-efi.img,id=d0,if=none,bus=0,unit=0 \
-device ide-hd,drive=d0,bus=ide.0
```
It will happen
![Screenshot from 2024-05-22 18-21-21](https://github.com/sbwml/openwrt_with_glibc/assets/34128783/52c7d31f-8528-4c6b-ba9e-e00ce311e7ce)

**Comment by sbwml** [comment]
微架构缘故，最新上传的固件已经修复 qemu 兼容。
![image](https://github.com/sbwml/openwrt_with_glibc/assets/16485166/95b01f52-d3dd-4868-ae5a-85c7f949a909)


值得注意的是：这个仓库是 OpenWrt GNU C 测试仓库，它不被维护，同时也没有 OpenWrt 官方软件生态（opkg）。
